name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  unit_test_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache-dependency-path: go.mod

      - name: Execute Backend Unit Tests
        working-directory: ./bugtracker-backend
        run: |
          go test -v ./...
          
          